"""Graph-only S4 and D6h actions, versioned separately from frozen E3 C2/C3.

S4 is represented by an improper four-fold generator.  D6h is represented by
the D6 graph action generated by ``r`` and ``s`` plus a horizontal reflection
whose atom permutation is identity; the latter deliberately constrains every
atom to the molecular plane without reading coordinates.
"""

from __future__ import annotations

from typing import Any

import networkx as nx
import numpy as np

from generative_model.models.graph_pg_3d_projection import (
    operation_errors,
    project_reynolds,
)
from generative_model.symmetry.graph_action import (
    _as_graph_fields,
    _build_normalized_heavy_graph,
    _extract_orbits,
    _lift_hydrogens,
    _permutation_power,
    _terminal_resonance_groups,
    recover_cyclic_graph_action,
)


SCHEMA_VERSION = "graph-only-full-target-action-v2"
SUPPORTED_TARGETS = ("C2", "C3", "S4", "D6h")


def _permutation_order(permutation: np.ndarray, maximum: int = 24) -> int | None:
    identity = np.arange(len(permutation), dtype=np.int64)
    for order in range(1, maximum + 1):
        if np.array_equal(_permutation_power(permutation, order), identity):
            return order
    return None


def _rotation_z(order: int, power: int = 1) -> np.ndarray:
    angle = 2.0 * np.pi * power / order
    cosine, sine = np.cos(angle), np.sin(angle)
    matrix = np.asarray([
        [cosine, -sine, 0.0],
        [sine, cosine, 0.0],
        [0.0, 0.0, 1.0],
    ], dtype=np.float64)
    matrix[np.abs(matrix) < 1e-15] = 0.0
    return matrix


def _s4_matrices() -> np.ndarray:
    generator = _rotation_z(4) @ np.diag([1.0, 1.0, -1.0])
    matrices = [np.linalg.matrix_power(generator, power) for power in range(4)]
    result = np.stack(matrices).astype(np.float64)
    result[np.abs(result) < 1e-15] = 0.0
    return result


def _d6h_matrices_and_permutations(
    rotation: np.ndarray, secondary: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    rotation_matrix = _rotation_z(6)
    secondary_matrix = np.diag([1.0, -1.0, -1.0])
    horizontal_matrix = np.diag([1.0, 1.0, -1.0])
    identity_permutation = np.arange(len(rotation), dtype=np.int64)
    matrices = []
    permutations = []
    for horizontal_power in range(2):
        for secondary_power in range(2):
            for rotation_power in range(6):
                r_matrix = np.linalg.matrix_power(rotation_matrix, rotation_power)
                matrix = (
                    np.linalg.matrix_power(horizontal_matrix, horizontal_power)
                    @ np.linalg.matrix_power(secondary_matrix, secondary_power)
                    @ r_matrix
                )
                r_permutation = _permutation_power(rotation, rotation_power)
                s_permutation = (
                    secondary if secondary_power else identity_permutation
                )
                # With NumPy advanced indexing and X R.T = X[p], the chosen
                # S @ R^k matrix convention pairs with s[r^k].
                permutation = s_permutation[r_permutation]
                matrices.append(matrix)
                permutations.append(permutation)
    result_matrices = np.stack(matrices).astype(np.float64)
    result_matrices[np.abs(result_matrices) < 1e-15] = 0.0
    return result_matrices, np.stack(permutations).astype(np.int64)


def _enumerate_heavy_automorphisms(
    fields: Any, maximum_search_matches: int
) -> tuple[list[np.ndarray], np.ndarray, dict[str, Any]]:
    graph, heavy_atoms, _, normalized_terminal_count = _build_normalized_heavy_graph(
        fields
    )
    matcher = nx.algorithms.isomorphism.GraphMatcher(
        graph,
        graph,
        node_match=lambda left, right: left["label"] == right["label"],
        edge_match=lambda left, right: left["label"] == right["label"],
    )
    automorphisms: list[np.ndarray] = []
    for match_count, mapping in enumerate(matcher.isomorphisms_iter(), start=1):
        if match_count > maximum_search_matches:
            raise RuntimeError(
                "extended graph-action automorphism search 超过冻结 match 上限 "
                f"{maximum_search_matches}"
            )
        automorphisms.append(np.asarray(
            [mapping[index] for index in range(len(heavy_atoms))], dtype=np.int64
        ))
    if not automorphisms:
        raise RuntimeError("normalized heavy graph 未返回 identity automorphism")
    return automorphisms, heavy_atoms, {
        "heavy_atom_count": len(heavy_atoms),
        "automorphism_count": len(automorphisms),
        "normalized_terminal_atom_count": normalized_terminal_count,
        "maximum_search_matches": maximum_search_matches,
    }


def _score_full_permutations(permutations: np.ndarray) -> tuple[Any, ...]:
    identity = np.arange(permutations.shape[1], dtype=np.int64)
    moved_any = np.any(permutations != identity[None, :], axis=0)
    maximum_moved = max(int(np.sum(value != identity)) for value in permutations)
    return (
        -int(np.sum(moved_any)),
        -maximum_moved,
        tuple(permutations.ravel().tolist()),
    )


def _recover_s4(fields: Any, maximum_search_matches: int) -> dict[str, Any]:
    automorphisms, heavy_atoms, audit = _enumerate_heavy_automorphisms(
        fields, maximum_search_matches
    )
    candidates = [
        permutation for permutation in automorphisms
        if _permutation_order(permutation) == 4
    ]
    if not candidates:
        raise ValueError("canonical graph 不存在 exact-order-4 S4 automorphism")
    scored = []
    for heavy in candidates:
        full = _lift_hydrogens(heavy, heavy_atoms, fields)
        powers = np.stack([_permutation_power(full, power) for power in range(4)])
        scored.append((_score_full_permutations(powers), full, powers))
    _, generator, permutations = min(scored, key=lambda value: value[0])
    audit.update({
        "selection_rule": (
            "exact order 4; maximum atoms moved by the group, then maximum "
            "single-operation support, then lexicographic action"
        ),
        "exact_order_candidate_count": len(candidates),
        "selected_generator_order": _permutation_order(generator),
    })
    return {
        "operation_matrices": _s4_matrices(),
        "permutation_index": permutations,
        "recovery_audit": audit,
    }


def _recover_d6h(fields: Any, maximum_search_matches: int) -> dict[str, Any]:
    graph, heavy_atoms, _, normalized_terminal_count = _build_normalized_heavy_graph(
        fields
    )
    matcher = nx.algorithms.isomorphism.GraphMatcher(
        graph,
        graph,
        node_match=lambda left, right: left["label"] == right["label"],
        edge_match=lambda left, right: left["label"] == right["label"],
    )
    rotations: list[np.ndarray] = []
    involutions: list[np.ndarray] = []
    selected: tuple[np.ndarray, np.ndarray] | None = None
    match_count = 0

    def valid_pair(rotation: np.ndarray, secondary: np.ndarray) -> bool:
        inverse = _permutation_power(rotation, 5)
        if not np.array_equal(secondary[rotation[secondary]], inverse):
            return False
        generated = {
            tuple(_permutation_power(rotation, power).tolist())
            for power in range(6)
        }
        generated.update(
            tuple(_permutation_power(rotation, power)[secondary].tolist())
            for power in range(6)
        )
        return len(generated) == 12

    # GraphMatcher enumeration is deterministic for the fixed canonical graph.
    # Stop at the first valid dihedral pair instead of materializing every
    # automorphism and taking an O(|R||S|) Cartesian product.
    for match_count, mapping in enumerate(matcher.isomorphisms_iter(), start=1):
        if match_count > maximum_search_matches:
            raise RuntimeError(
                "D6h streaming automorphism search 超过冻结 match 上限 "
                f"{maximum_search_matches}"
            )
        permutation = np.asarray(
            [mapping[index] for index in range(len(heavy_atoms))], dtype=np.int64
        )
        order = _permutation_order(permutation)
        if order == 6:
            for secondary in involutions:
                if valid_pair(permutation, secondary):
                    selected = (permutation, secondary)
                    break
            rotations.append(permutation)
        elif order == 2:
            for rotation in rotations:
                if valid_pair(rotation, permutation):
                    selected = (rotation, permutation)
                    break
            involutions.append(permutation)
        if selected is not None:
            break
    if selected is None:
        raise ValueError(
            "canonical graph 不存在满足 r^6=e, s^2=e, srs=r^-1 的 D6 action"
        )
    heavy_rotation, heavy_secondary = selected
    rotation = _lift_hydrogens(heavy_rotation, heavy_atoms, fields)
    secondary = _lift_hydrogens(heavy_secondary, heavy_atoms, fields)
    matrices, permutations = _d6h_matrices_and_permutations(rotation, secondary)
    audit = {
        "heavy_atom_count": len(heavy_atoms),
        "automorphism_count": match_count,
        "automorphism_enumeration_complete": False,
        "normalized_terminal_atom_count": normalized_terminal_count,
        "maximum_search_matches": maximum_search_matches,
        "selection_rule": (
            "first GraphMatcher-ordered pair satisfying r order 6, s order 2, "
            "srs=r^-1 and 12 unique D6 graph actions"
        ),
        "exact_order_6_candidate_count": len(rotations),
        "exact_order_2_candidate_count": len(involutions),
        "valid_dihedral_pair_count": 1,
        "horizontal_reflection_permutation": "identity (graph-only planar D6h contract)",
        "selected_rotation_order": _permutation_order(rotation),
        "selected_secondary_order": _permutation_order(secondary),
    }
    return {
        "operation_matrices": matrices,
        "permutation_index": permutations,
        "recovery_audit": audit,
    }


def _validate_graph_preservation(action: dict[str, Any], fields: Any) -> dict[str, Any]:
    matrices = np.asarray(action["operation_matrices"], dtype=np.float64)
    permutations = np.asarray(action["permutation_index"], dtype=np.int64)
    atom_count = len(fields.atomic_numbers)
    expected_order = {"S4": 4, "D6h": 24}[str(action["target_pg"])]
    if matrices.shape != (expected_order, 3, 3):
        raise ValueError("extended operation matrix shape 非法")
    if permutations.shape != (expected_order, atom_count):
        raise ValueError("extended permutation shape 非法")
    identity = np.arange(atom_count, dtype=np.int64)
    if not np.array_equal(permutations[0], identity):
        raise ValueError("extended action 第一项必须为 identity")
    if any(not np.array_equal(np.sort(value), identity) for value in permutations):
        raise ValueError("extended action 含非双射 permutation")
    if not np.array_equal(
        fields.atomic_numbers[permutations],
        np.broadcast_to(fields.atomic_numbers, permutations.shape),
    ):
        raise ValueError("extended action 跨元素映射")
    matrix_keys = {tuple(np.round(matrix, 12).ravel()) for matrix in matrices}
    if len(matrix_keys) != expected_order:
        raise ValueError("extended operation matrices 不构成完整目标群")
    edge_set = set(fields.edge_types)
    terminal_to_group, _ = _terminal_resonance_groups(fields)
    normalized_operation_count = 0
    for permutation in permutations:
        mapped_edges = {
            tuple(sorted((int(permutation[left]), int(permutation[right]))))
            for left, right in edge_set
        }
        if mapped_edges != edge_set:
            raise ValueError("extended permutation 修改 connectivity")
        normalized = False
        for atom, mapped in enumerate(permutation):
            source_features = (
                int(fields.formal_charges[atom]),
                int(fields.radical_electrons[atom]),
                bool(fields.aromaticity[atom]),
            )
            target_features = (
                int(fields.formal_charges[mapped]),
                int(fields.radical_electrons[mapped]),
                bool(fields.aromaticity[mapped]),
            )
            if source_features != target_features:
                if atom not in terminal_to_group:
                    raise ValueError("extended action 修改非共振 atom labels")
                normalized = True
        for pair, kind in fields.edge_types.items():
            mapped_pair = tuple(sorted((
                int(permutation[pair[0]]), int(permutation[pair[1]])
            )))
            if fields.edge_types[mapped_pair] != kind:
                terminal = pair[0] if pair[0] in terminal_to_group else pair[1]
                if terminal not in terminal_to_group:
                    raise ValueError("extended action 修改非共振 bond type")
                normalized = True
        normalized_operation_count += int(normalized)

    orbit_id, orbit_size = _extract_orbits(permutations)
    if not np.array_equal(orbit_id, np.asarray(action["orbit_id"], dtype=np.int64)):
        raise ValueError("extended orbit_id 与 action 不一致")
    if not np.array_equal(orbit_size, np.asarray(action["orbit_size"], dtype=np.int64)):
        raise ValueError("extended orbit_size 与 action 不一致")
    probe = np.arange(atom_count * 3, dtype=np.float64).reshape(atom_count, 3)
    probe = np.sin(probe * 0.37) + np.cos(probe * 0.11)
    projected = project_reynolds(probe, matrices, permutations)
    errors = operation_errors(projected, matrices, permutations)
    if errors["max_atom_error_angstrom"] > 1e-10:
        raise ValueError("extended action 的 Reynolds projection 非幂等群投影")
    return {
        "atom_count": atom_count,
        "operation_count": expected_order,
        "unique_permutation_count": len({tuple(value) for value in permutations}),
        "orbit_count": int(orbit_id.max()) + 1,
        "moved_atom_count": int(np.sum(np.any(
            permutations != identity[None, :], axis=0
        ))),
        "resonance_normalized_operation_count": normalized_operation_count,
        "projection_probe_max_operation_error_angstrom": float(
            errors["max_atom_error_angstrom"]
        ),
    }


def recover_full_target_graph_action(
    atomic_numbers: np.ndarray,
    formal_charges: np.ndarray,
    radical_electrons: np.ndarray,
    bond_index: np.ndarray,
    bond_types: np.ndarray,
    target_pg: str,
    *,
    maximum_search_matches: int = 100_000,
) -> dict[str, Any]:
    """Recover C2/C3/S4/D6h without coordinates or stored symmetry actions."""

    if target_pg not in SUPPORTED_TARGETS:
        raise ValueError(f"不支持的 target_pg: {target_pg}")
    if target_pg in {"C2", "C3"}:
        return recover_cyclic_graph_action(
            atomic_numbers,
            formal_charges,
            radical_electrons,
            bond_index,
            bond_types,
            target_pg,
            maximum_search_matches=min(maximum_search_matches, 10_000),
        )
    if maximum_search_matches <= 0:
        raise ValueError("maximum_search_matches 必须为正")
    fields = _as_graph_fields(
        atomic_numbers, formal_charges, radical_electrons, bond_index, bond_types
    )
    recovered = (
        _recover_s4(fields, maximum_search_matches)
        if target_pg == "S4"
        else _recover_d6h(fields, maximum_search_matches)
    )
    permutations = np.asarray(recovered["permutation_index"], dtype=np.int64)
    orbit_id, orbit_size = _extract_orbits(permutations)
    action: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "target_pg": target_pg,
        "operation_matrices": recovered["operation_matrices"],
        "permutation_index": permutations,
        "orbit_id": orbit_id,
        "orbit_size": orbit_size,
        "recovery_audit": {
            **recovered["recovery_audit"],
            "coordinates_read": False,
            "stored_symmetry_action_read": False,
        },
    }
    action["validation"] = _validate_graph_preservation(action, fields)
    return action
